import AuthProvider from "@/contexts/authProvider";
import { CartProvider } from "@/contexts/cartProvider";
import "./globals.css";

export const metadata = {
  title: "Shopping Cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <CartProvider>{children}</CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
